### ISSUE TITLE
In E2E tests, fastify-request-context is not closing properly after calling fastify.close()

### ISSUE THREAD

**Issue by jlongo-daitan** [fastify/fastify-request-context#108]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.28.0

### Plugin version

2.2.0

### Node.js version

16.3.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04.4 LTS

### Description

When running E2E tests, even calling `fastify.close()`, Jest is reporting an open handle from `fastify-request-context`:

`
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  fastify-request-context

      35 |   it('test', (done) => {
      36 |     console.log('test');
    > 37 |     fastify.inject({
         |             ^
      38 |         method: 'GET',
      39 |         url: '/'
      40 |       }, (err, response) => {

      at Object.ready (node_modules/fastify/fastify.js:481:13)
      at Object.inject (node_modules/fastify/fastify.js:459:12)
      at Object.<anonymous> (test.js:37:13)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)
`

### Steps to Reproduce

package.json:

```
{
    "name": "test",
    "version": "1.0.0",
    "scripts": {
        "test": "jest  --detectOpenHandles"
    },
    "dependencies": {
        "fastify": "3.28.0",
        "fastify-request-context": "2.2.0"
    },
    "devDependencies": {
        "jest": "27.5.1"
    }
}
```

test.js:

```
const Fastify = require('fastify');
const { requestContext, fastifyRequestContextPlugin } = require('fastify-request-context');

async function buildFastify () {
  const fastify = Fastify();

  fastify.get('/', function (request, reply) {
    reply.send({ hello: 'world' });
  });

  // If we comment the following lines, no open handles
  await fastify.register(fastifyRequestContextPlugin, {
    hook: 'onRequest',
    defaultStoreValues: {},
  });
  fastify.addHook('preValidation', (request, _reply, done) => {
    requestContext.set('body', request.body);
    done();
  });

  return fastify;
};

describe('GET `/` route', () => {
  let fastify;

  beforeAll(async () => {
    fastify = await buildFastify();
  });

  afterAll(async () => {
    await fastify.close();
  });

  it('test', (done) => {
    fastify.inject({
        method: 'GET',
        url: '/'
      }, (err, response) => {
        expect(response.statusCode).toEqual(200);
        done();
      });
  });  
})
```

Steps to reproduce:
1. Create the files above
2. npm install
3. npm run test
4. Most of the times Jest will say there is an open handle related to `fastify-request-context`

### Expected Behavior

There shouldn't be any open handles in an E2E test after calling `fastify.close()`

**Comment by jsumners** [comment]
Does this happen without Jest?

**Comment by mcollina** [comment]
This is a limitation of Jest.

**Comment by jlongo-daitan** [comment]
This is not a limitation of Jest. Jest has a nice feature that checks if we are not closing properly the resources at the end of the tests. Without 'fastify-request-context', there is no issue. Also, Jest is telling us there are pending resources with 'fastify-request-context'.

**Comment by mcollina** [comment]
That's how the request context work. There is likely something that has becomes part of your promise chain. It's likely safe.

**Comment by climba03003** [comment]
This library actually tested with `jest`. If it has problem with `open handles`, the test should be failed.
I have follow your repro and it is actually no error on my end.

```shell
$ node -v
v16.14.0

$ jest  --detectOpenHandles
 PASS  ./test.js
  GET `/` route
    ✓ test (698 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.815 s
Ran all test suites.
Done in 6.83s.
```

**Comment by jlongo-daitan** [comment]
Note that I enabled the option "--detectOpenHandles". The test won't fail if there are open handles, but it's a warning the code is not closing all resources properly.

@climba03003 no, the scenario I sent just contains those files.

Is there a way I can force "fastify-request-context" to close?

**Comment by climba03003** [comment]
> Note that I enabled the option "--detectOpenHandles". The test won't fail if there are open handles, but it's a warning the code is not closing all resources properly.
> 
> @climba03003 no, the scenario I sent just contains those files.
> 
> Is there a way I can force "fastify-request-context" to close?

You can see my command is running `jest  --detectOpenHandles`. And all works very well.
![image](https://user-images.githubusercontent.com/23028015/163239701-ac93e8de-26c0-458a-bc5d-83160a1c3887.png)

**Comment by jlongo-daitan** [comment]
It seems like an issue with the Node version I was using. See this:

With Node 16.4:
```
jlongo@x:~/git/test$ nvm use 16.14
Now using node v16.14.2 (npm v8.5.0)
jlongo@x:~/git/test$ ./node_modules/.bin/jest --detectOpenHandles
 PASS  ./test.js
  GET `/` route
    ✓ test (73 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.325 s, estimated 1 s
Ran all test suites.
```

With Node 16.3.2:
```
jlongo@x:~/git/test$ nvm use 16.13.2
Now using node v16.13.2 (npm v8.1.2)
jlongo@x:~/git/test$ ./node_modules/.bin/jest --detectOpenHandles
 PASS  ./test.js
  GET `/` route
    ✓ test (71 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.331 s, estimated 1 s
Ran all test suites.

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  fastify-request-context

      34 |
      35 |   it('test', (done) => {
    > 36 |     fastify.inject({
         |             ^
      37 |         method: 'GET',
      38 |         url: '/'
      39 |       }, (err, response) => {

      at Object.ready (node_modules/fastify/fastify.js:481:13)
      at Object.inject (node_modules/fastify/fastify.js:459:12)
      at Object.<anonymous> (test.js:36:13)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)
 ```
 
 Thanks!
