### ISSUE TITLE
Please publish version 3.1.1 to npm

### ISSUE THREAD

**Issue by billxinli** [fastify/fastify-request-context#138]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

https://github.com/fastify/fastify-request-context/blob/v3.1.1/package.json#L38

Is it possible to publish 3.1.1 to npm? 

https://www.npmjs.com/package/@fastify/request-context

3.1.0 resolves to fastify-plugin v4.

Thank you!

**Comment by Uzlopak** [comment]
@mcollina

**Comment by kibertoad** [comment]
I'll publish tomorrow

**Comment by Eomm** [comment]
I was at pc and I released it:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/11404065/199176705-a11a8f30-2534-40af-9714-b37d128e28a2.png">

Thanks for reporting 👍🏽

**Comment by billxinli** [comment]
Thank you all!
