### ISSUE TITLE
Stricter default context interface?

### ISSUE THREAD

**Issue by voxpelli** [fastify/fastify-request-context#159]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I would propose swapping this:

```typescript
  export interface RequestContextData {
    [key: string]: any
  }
```

For plain:

```typescript
  export interface RequestContextData {
  }
```

### Motivation

This way someone like me who wants to get help ensuring I don't mistype any context names can use this plugin really strictly typed, and if someone wants to be lenient on the key names but strict with the types, then they could easily do:

```typescript
declare module '@fastify/request-context' {
  interface RequestContextData {
    [key: string]: unknown
  }
}
```

And those who wants to have it like today can simply do:

```typescript
declare module '@fastify/request-context' {
  interface RequestContextData {
    [key: string]: any
  }
}
```

By leaving out the default `[key: string]: any` it becomes possible to customize the type in ways otherwise not possible.

**Comment by Uzlopak** [comment]
interface bla { } is afaik disencouraged, because then you could assign everything to the variable. E.g. 

```typescript
interface A {
}

const emptyObject1:A = {} // works
const num1: A = 3 // works

interface B {
    [key:string]: any
}

const emptyObject2:B = {} // works
const num2: B = 3 // error
```

**Comment by voxpelli** [comment]
```ts
interface A {
  _?: never
}
```

Something like that would be preferable then? A sacrificial key to make it be interpreted as an object?

**Comment by voxpelli** [comment]
As can be seen in this [TS Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEoQI4FcIGcwDCA9uBAB5gAicYcyA3gL4BQzYAngA4oDmEYAHgDSycpBAATXMgDWEdkRhpMOfMVIVqtAHzIAvMgAUc9gC5kQgJT7d6bHkIlImmnADaQgLrIAPsiySEDCgEBIA3Kwc3MgAYkRE+sh8ggDkMPEp2kA) I think the empty interface works correctly for this module (and of course should never actually be empty in practice as amy typed user will extend it):

![Skärmavbild 2023-06-12 kl  00 05 42](https://github.com/fastify/fastify-request-context/assets/34457/dc57dcee-5700-41cb-ae00-653213e01d20)

**Comment by kibertoad** [comment]
sounds good to me. needs documentation and tsd test
